trigger:
  - main

pool: 'TfsOracle'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Production Environment'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Production Environment'
    repository: 'naseejsa/gokb'
    command: 'buildAndPush'
    tags: '1.0.1'
    Dockerfile: '**/Dockerfile'

