[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.2"
version_files = [
    "commitizen.conf:version"
]
tag_format = "v$major.$minor.$patch$prerelease"
bump_message="bump_message='version $current_version → $new_version'"
annotated_tag = true